name: Build .Net MAUI winOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dotnet maui workload
      run: dotnet workload install maui
    - name: Build
      run: dotnet build Sofia-s-Ladybugs.csproj -c Release -f:net9.0-windows10.0.19041.0
